FROM ubuntu:19.10

RUN mkdir /code

WORKDIR /code

RUN apt-get update

RUN apt-get install -y nginx

Run echo "Hello World"

ADD example.sh /code/

ADD start_app.sh /code/

RUN chmod +x example.sh && chmod +x start_app.sh

RUN ./example.sh && ./star_app.sh
